'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WebServiceImage
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WebServiceImage.WebServiceSoap")>  _
    Public Interface WebServiceSoap
        
        'CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendImage", ReplyAction:="*")>  _
        Function SendImage(ByVal request As WebServiceImage.SendImageRequest) As WebServiceImage.SendImageResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SendImage", ReplyAction:="*")>  _
        Function SendImageAsync(ByVal request As WebServiceImage.SendImageRequest) As System.Threading.Tasks.Task(Of WebServiceImage.SendImageResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendImageRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendImage", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WebServiceImage.SendImageRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceImage.SendImageRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendImageRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public id As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public image() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As String, ByVal image() As Byte)
            MyBase.New
            Me.id = id
            Me.image = image
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendImageResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendImageResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WebServiceImage.SendImageResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceImage.SendImageResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendImageResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public SendImageResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendImageResult As Boolean)
            MyBase.New
            Me.SendImageResult = SendImageResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebServiceSoapChannel
        Inherits WebServiceImage.WebServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of WebServiceImage.WebServiceSoap)
        Implements WebServiceImage.WebServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceImage_WebServiceSoap_SendImage(ByVal request As WebServiceImage.SendImageRequest) As WebServiceImage.SendImageResponse Implements WebServiceImage.WebServiceSoap.SendImage
            Return MyBase.Channel.SendImage(request)
        End Function
        
        Public Function SendImage(ByVal id As String, ByVal image() As Byte) As Boolean
            Dim inValue As WebServiceImage.SendImageRequest = New WebServiceImage.SendImageRequest()
            inValue.Body = New WebServiceImage.SendImageRequestBody()
            inValue.Body.id = id
            inValue.Body.image = image
            Dim retVal As WebServiceImage.SendImageResponse = CType(Me,WebServiceImage.WebServiceSoap).SendImage(inValue)
            Return retVal.Body.SendImageResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceImage_WebServiceSoap_SendImageAsync(ByVal request As WebServiceImage.SendImageRequest) As System.Threading.Tasks.Task(Of WebServiceImage.SendImageResponse) Implements WebServiceImage.WebServiceSoap.SendImageAsync
            Return MyBase.Channel.SendImageAsync(request)
        End Function
        
        Public Function SendImageAsync(ByVal id As String, ByVal image() As Byte) As System.Threading.Tasks.Task(Of WebServiceImage.SendImageResponse)
            Dim inValue As WebServiceImage.SendImageRequest = New WebServiceImage.SendImageRequest()
            inValue.Body = New WebServiceImage.SendImageRequestBody()
            inValue.Body.id = id
            inValue.Body.image = image
            Return CType(Me,WebServiceImage.WebServiceSoap).SendImageAsync(inValue)
        End Function
    End Class
End Namespace
